feat: add --silent option
gilamran/tsc-watch pull request #132
Opened 2021-12-18 18:48 UTC by fmvilas

This adds another option: `--silent`. This option enables you not to show any logs on the console.

I'm using this module as a library on [Glee](https://www.github.com/asyncapi/glee) and the compilation is a process that should happen behind the scenes, without the user noticing.

I thought this would be useful for others too.

Cheers, and thanks for the great work! 🙌

2021-12-18 21:09 UTC, gilamran requested changes

2021-12-18 21:09 UTC, gilamran commented on lib/tsc-watch.js
> +  if (!silent) print(noColors, noClear, line);
please convert to a block syntax:
```
if (!silent) {
  print(noColors, noClear, line);
}
```

2021-12-19 11:02 UTC, fmvilas commented on lib/tsc-watch.js
> +  if (!silent) print(noColors, noClear, line);
Done 👍

2021-12-20 14:07 UTC, gilamran commented
Thanks, I'll merge and release later today.

2021-12-20 20:22 UTC, merged

2021-12-20 20:25 UTC, gilamran commented
Released on version 4.6.0

2021-12-20 20:51 UTC, fmvilas commented
Thank you! 🚀